import { StyleSheet } from 'react-native';

import { storybookTheme } from '@/shared/ui';

// reader-card UI 전체가 공유하는 하나의 스타일시트로, 컴포넌트별로 분리하지 않고
// 여기 한곳에 모아둔다: 많은 키(contentGroup, questionEyebrow, secondaryButtonFull 등)가
// 이미 여러 패널에서 재사용되고 있어서, 이를 나누어 놓으면 어느 패널이 어느 키를
// 소유하는지 추적하기 어려워지는 위험이 있다.
// 버튼 스타일은 대신 shared/ui/action-button에 있다(그 마크업은 이 스타일들과 달리
// 약 15개의 호출 지점에 그대로 중복되어 있었다).
export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#161025' },
  app: { flex: 1, backgroundColor: '#161025', overflow: 'hidden' },
  imageShade: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    backgroundColor: 'rgba(18, 10, 30, 0.12)',
  },
  reportHiddenIllustration: { opacity: 0 },
  reportPageBackground: {
    backgroundColor: '#FFF9ED',
  },
  topBar: {
    position: 'absolute',
    left: 24,
    right: 24,
    top: 18,
    zIndex: storybookTheme.zIndex.sticky,
    gap: 10,
  },
  topBarCompactPlayback: {
    left: 12,
    right: 12,
    top: 10,
  },
  topBarRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  reportTopBar: {
    left: 0,
    right: 0,
    top: 0,
    minHeight: 84,
    paddingHorizontal: 20,
    paddingVertical: 12,
    backgroundColor: '#FFF9ED',
    borderBottomWidth: 1,
    borderBottomColor: '#E7DCC9',
    shadowColor: '#2E1948',
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
  },
  brandLockup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flexShrink: 1,
  },
  brandLockupCompactPlayback: { display: 'none' },
  brandLogoFrame: {
    width: 50,
    height: 54,
    borderRadius: storybookTheme.radius.logoFrame,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 249, 237, 0.96)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.72)',
  },
  reportBrandLogoFrame: {
    backgroundColor: 'transparent',
    borderColor: 'transparent',
  },
  brandLogo: { width: 42, height: 46 },
  brandTextLockup: { gap: 4, flexShrink: 1 },
  brand: {
    color: '#FFFFFF',
    fontSize: storybookTheme.type.xs,
    fontWeight: '700',
    letterSpacing: 1.8,
  },
  brandQ: { color: '#F6C64D' },
  reportTopText: { color: '#2B1748' },
  storyTitle: {
    color: '#FFFFFF',
    fontSize: storybookTheme.type.md,
    lineHeight: 21,
    fontWeight: '700',
  },
  reportStoryTitle: { color: '#6B5C80' },
  chapterTitle: {
    color: 'rgba(255, 255, 255, 0.72)',
    fontSize: storybookTheme.type.xs,
    lineHeight: 15,
    fontWeight: '600',
  },
  topRight: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 9,
  },
  topRightCompactPlayback: {
    width: '100%',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 6,
  },
  topPlaybackControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  topPlaybackControlsCompact: {
    width: '100%',
    justifyContent: 'center',
  },
  topControlButton: {
    minWidth: 38,
    minHeight: 38,
    paddingHorizontal: 11,
    borderRadius: storybookTheme.radius.pill,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    backgroundColor: 'rgba(22, 12, 36, 0.72)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.22)',
  },
  topControlButtonPrimary: {
    borderColor: 'rgba(246,198,77,0.7)',
    backgroundColor: 'rgba(45, 25, 53, 0.86)',
  },
  topControlIcon: {
    minWidth: 13,
    color: '#F6C64D',
    fontSize: storybookTheme.type.sm,
    fontWeight: '700',
    textAlign: 'center',
  },
  topControlText: {
    color: '#FFFFFF',
    fontSize: storybookTheme.type.xxs,
    fontWeight: '700',
  },
  progressPill: {
    backgroundColor: 'rgba(22, 12, 36, 0.78)',
    borderColor: 'rgba(255,255,255,0.25)',
    borderWidth: 1,
    borderRadius: storybookTheme.radius.pill,
    paddingHorizontal: 15,
    paddingVertical: 8,
  },
  progressPillCompact: {
    minHeight: 38,
    borderRadius: storybookTheme.radius.pill,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.25)',
    backgroundColor: 'rgba(22, 12, 36, 0.78)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 13,
  },
  progressText: { color: '#FFFFFF', fontWeight: '700', fontSize: storybookTheme.type.sm },
  reportBackButton: {
    minHeight: 40,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#CDBEDF',
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 15,
  },
  reportBackButtonText: {
    color: '#34204D',
    fontSize: storybookTheme.type.sm,
    fontWeight: '700',
  },
  sceneProgress: {
    position: 'absolute',
    left: 24,
    right: 24,
    top: 86,
    zIndex: storybookTheme.zIndex.sticky,
    flexDirection: 'row',
    gap: 5,
  },
  sceneProgressCompactPlayback: { left: 12, right: 12, top: 100 },
  progressSegment: {
    flex: 1,
    height: 3,
    borderRadius: 99,
    backgroundColor: 'rgba(255,255,255,0.28)',
    overflow: 'hidden',
  },
  progressSegmentFill: {
    height: '100%',
    borderRadius: 99,
    backgroundColor: '#F6C64D',
  },
  scrollContent: {
    flexGrow: 1,
    minHeight: '100%',
    paddingHorizontal: 16,
    paddingTop: 112,
    paddingBottom: 20,
  },
  scrollContentWide: { paddingHorizontal: 34, paddingBottom: 28 },
  scrollContentShort: { paddingTop: 98, paddingBottom: 12 },
  scrollContentPlayback: { paddingBottom: 18 },
  scrollContentCompactPlayback: { paddingTop: 116 },
  scrollContentCentered: { justifyContent: 'center' },
  scrollContentShortCentered: { justifyContent: 'flex-start' },
  reportScrollContent: {
    justifyContent: 'flex-start',
    paddingTop: 102,
    paddingBottom: 54,
  },
  reportScrollContentWide: {
    paddingHorizontal: 40,
    paddingBottom: 72,
  },
  spacer: { flex: 1, minHeight: 220 },
  playbackSpacer: { minHeight: 360 },
  readerCard: {
    width: '100%',
    maxWidth: 760,
    alignSelf: 'center',
    backgroundColor: 'rgba(255, 252, 245, 0.96)',
    borderRadius: 28,
    padding: 22,
    gap: 18,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.74)',
    shadowColor: '#12091F',
    shadowOpacity: 0.35,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 9 },
  },
  readerCardWide: { maxWidth: 850, paddingHorizontal: 30, paddingVertical: 24 },
  onboardingCard: { maxWidth: 640 },
  interactionCard: {
    maxWidth: 680,
    backgroundColor: 'rgba(255, 252, 245, 0.94)',
  },
  reportReaderCard: {
    maxWidth: 1080,
    padding: 0,
    gap: 0,
    borderWidth: 0,
    borderRadius: 0,
    backgroundColor: 'transparent',
    shadowOpacity: 0,
  },
  playbackCard: {
    maxWidth: 880,
    minHeight: 82,
    borderRadius: 16,
    paddingHorizontal: 18,
    paddingVertical: 10,
    gap: 6,
    backgroundColor: 'rgba(16, 8, 28, 0.66)',
    borderColor: 'rgba(255,255,255,0.16)',
    shadowOpacity: 0.22,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 5 },
  },
  playbackCardCollapsed: { maxWidth: 250, minHeight: 42 },
  cardMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  statusPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    backgroundColor: '#F2EAF8',
    borderRadius: storybookTheme.radius.pill,
    paddingHorizontal: 11,
    paddingVertical: 7,
  },
  statusDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: '#7B4AA1',
  },
  statusText: { color: '#573570', fontSize: storybookTheme.type.xxs, fontWeight: '700' },
  contentGroup: { gap: 15 },
  heroTitle: {
    color: '#28153F',
    fontSize: storybookTheme.type.xxl,
    lineHeight: 39,
    fontWeight: '700',
    textAlign: 'center',
  },
  introBody: {
    color: '#5E5367',
    fontSize: storybookTheme.type.md,
    lineHeight: 25,
    textAlign: 'center',
  },
  nameField: {
    gap: 7,
    backgroundColor: '#F7F1FA',
    borderRadius: 18,
    padding: 14,
  },
  nameLabel: { color: '#4E3267', fontSize: storybookTheme.type.xs, fontWeight: '700' },
  nameInput: {
    height: 50,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: '#D8C8E2',
    backgroundColor: '#FFFFFF',
    color: '#2A173F',
    fontSize: storybookTheme.type.md,
    fontWeight: '600',
    paddingHorizontal: 15,
  },
  nameHint: { color: '#6F5D85', fontSize: storybookTheme.type.xxs, lineHeight: 17 }, // WCAG AA 4.5:1 (원래 #85778E는 이 배경에서 4.4:1로 미달)
  typedQuestionInput: {
    minHeight: 120,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#D8C8E2',
    backgroundColor: '#FFFFFF',
    color: '#2A173F',
    fontSize: storybookTheme.type.md,
    lineHeight: 28,
    paddingHorizontal: 16,
    paddingVertical: 14,
    textAlignVertical: 'top',
  },
  typedQuestionCount: {
    color: '#7A6C82', // WCAG AA 4.5:1 (원래 #85778E는 카드 배경에서 4.08:1로 미달)
    fontSize: storybookTheme.type.xxs,
    textAlign: 'right',
  },
  parentHint: {
    color: '#6F5D85', // WCAG AA 4.5:1 (원래 #897C90는 흰 배경에서 3.92:1로 미달)
    fontSize: storybookTheme.type.xxs,
    lineHeight: 17,
    textAlign: 'center',
  },
  voiceConsentRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    borderWidth: 1,
    borderColor: '#D8C9E5',
    borderRadius: 14,
    backgroundColor: '#FAF7FC',
    paddingHorizontal: 13,
    paddingVertical: 12,
  },
  voiceConsentBox: {
    width: 22,
    height: 22,
    flexShrink: 0,
    borderWidth: 2,
    borderColor: '#76558D',
    borderRadius: 6,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  voiceConsentBoxChecked: {
    borderColor: '#43225F',
    backgroundColor: '#43225F',
  },
  voiceConsentCheck: {
    color: '#FFFFFF',
    fontSize: storybookTheme.type.md,
    lineHeight: 18,
    fontWeight: '700',
  },
  voiceConsentText: {
    flex: 1,
    color: '#66566E',
    fontSize: storybookTheme.type.xxs,
    lineHeight: 17,
  },
  voiceConsentLabel: {
    color: '#43225F',
    fontWeight: '700',
  },
  playbackContent: { gap: 5 },
  captionHeader: {
    minHeight: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  captionSpeakerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  playbackSpeaker: {
    color: '#F6C64D',
    fontSize: storybookTheme.type.xs,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  captionToggle: {
    minHeight: 34,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
    backgroundColor: 'rgba(255,255,255,0.11)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
  },
  captionToggleText: {
    color: '#F4EEF8',
    fontSize: storybookTheme.type.xxs,
    fontWeight: '700',
  },
  playbackSubtitle: {
    color: '#FFFFFF',
    fontSize: storybookTheme.type.md,
    lineHeight: 25,
    fontWeight: '600',
    textAlign: 'center',
    textShadowColor: 'rgba(0,0,0,0.32)',
    textShadowRadius: 3,
    textShadowOffset: { width: 0, height: 1 },
  },
  playbackControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  playbackButton: {
    flex: 1,
    minHeight: 45,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.18)',
    backgroundColor: 'rgba(255,255,255,0.10)',
    paddingHorizontal: 9,
  },
  playbackButtonPrimary: {
    borderColor: 'rgba(246,198,77,0.62)',
    backgroundColor: 'rgba(246,198,77,0.20)',
  },
  playbackButtonIcon: {
    color: '#F6C64D',
    fontSize: storybookTheme.type.md,
    fontWeight: '700',
  },
  playbackButtonText: {
    color: '#FFFFFF',
    fontSize: storybookTheme.type.xs,
    fontWeight: '700',
    textAlign: 'center',
  },
  playingDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#CFC4B0',
  },
  playingDotActive: { backgroundColor: '#E56B45' },
  questionEyebrow: {
    color: '#C4513B',
    fontSize: storybookTheme.type.xs,
    fontWeight: '700',
    letterSpacing: 0.8,
    textAlign: 'center',
  },
  questionTitle: {
    color: '#26143C',
    fontSize: storybookTheme.type.xl,
    lineHeight: 37,
    fontWeight: '700',
    textAlign: 'center',
  },
  questionHelp: {
    color: '#6F6277',
    fontSize: storybookTheme.type.sm,
    lineHeight: 22,
    textAlign: 'center',
  },
  questionListening: {
    minHeight: 58,
    borderRadius: 18,
    backgroundColor: '#FFF0E9',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  questionListeningText: {
    color: '#9B3F2D',
    fontSize: storybookTheme.type.sm,
    fontWeight: '700',
  },
  splitRow: { flexDirection: 'row', gap: 10 },
  recordingTitle: {
    color: '#28153F',
    fontSize: storybookTheme.type.lg,
    lineHeight: 31,
    fontWeight: '700',
    textAlign: 'center',
  },
  recordingTime: {
    color: '#D65C3F',
    fontSize: storybookTheme.type.xxl,
    fontWeight: '700',
    textAlign: 'center',
  },
  meterTrack: {
    height: 16,
    borderRadius: 99,
    backgroundColor: '#E8DDCF',
    overflow: 'hidden',
  },
  meterFill: {
    height: '100%',
    borderRadius: 99,
    backgroundColor: '#E96848',
  },
  recordingGuide: {
    color: '#766B7A',
    fontSize: storybookTheme.type.xs,
    textAlign: 'center',
  },
  panelTitle: {
    color: '#28153F',
    fontSize: storybookTheme.type.lg,
    lineHeight: 31,
    fontWeight: '700',
    textAlign: 'center',
  },
  recordingSummary: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: '#F3EDF6',
    borderRadius: 13,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  recordingSummaryText: { color: '#64546E', fontSize: storybookTheme.type.xs, fontWeight: '700' },
  previewButton: {
    minHeight: 50,
    borderRadius: 15,
    backgroundColor: '#F6C64D',
    alignItems: 'center',
    justifyContent: 'center',
  },
  previewButtonText: { color: '#2B183F', fontSize: storybookTheme.type.sm, fontWeight: '700' },
  loadingGroup: { alignItems: 'center', gap: 14, paddingVertical: 8 },
  loadingTitle: {
    color: '#28153F',
    fontSize: storybookTheme.type.lg,
    lineHeight: 32,
    fontWeight: '700',
    textAlign: 'center',
  },
  loadingBody: {
    color: '#716477',
    fontSize: storybookTheme.type.sm,
    lineHeight: 22,
    textAlign: 'center',
  },
  loadingDots: { flexDirection: 'row', gap: 7 },
  recoveryActions: { width: '100%', gap: 10, marginTop: 4 },
  loadingDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#8F61AA',
  },
  choiceList: { width: '100%', gap: 10 },
  choiceButton: {
    minHeight: 74,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 13,
    borderRadius: 18,
    borderWidth: 2,
    borderColor: '#DDC7E8',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 14,
    paddingVertical: 12,
    transform: [{ scale: 1 }],
    transitionProperty: 'transform, background-color',
    transitionDuration: '120ms',
    transitionTimingFunction: 'ease-out',
  } as never,
  choiceButtonPressed: {
    transform: [{ scale: 0.97 }],
    backgroundColor: '#F8F1FB',
  },
  choiceNumber: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F6C64D',
  },
  choiceNumberText: {
    color: '#38204D',
    fontSize: storybookTheme.type.md,
    fontWeight: '700',
  },
  choiceCopy: { flex: 1, gap: 3 },
  choiceLabel: { color: '#321A4A', fontSize: storybookTheme.type.md, fontWeight: '700' },
  choiceMeaning: { color: '#75647C', fontSize: storybookTheme.type.xs, lineHeight: 18 },
  changeBadge: {
    alignSelf: 'center',
    borderRadius: storybookTheme.radius.pill,
    backgroundColor: '#E7D8F1',
    paddingHorizontal: 13,
    paddingVertical: 8,
  },
  answerBadge: { backgroundColor: '#FFF0C8' },
  changeBadgeText: { color: '#57306E', fontSize: storybookTheme.type.xs, fontWeight: '700' },
  responseText: {
    color: '#28153F',
    fontSize: storybookTheme.type.lg,
    lineHeight: 33,
    fontWeight: '700',
    textAlign: 'center',
  },
  branchText: {
    color: '#55485E',
    fontSize: storybookTheme.type.md,
    lineHeight: 24,
    textAlign: 'center',
  },
  transcriptCard: {
    borderRadius: 15,
    backgroundColor: '#F2ECF5',
    padding: 13,
    gap: 4,
  },
  transcriptLabel: {
    color: '#7A687F',
    fontSize: storybookTheme.type.xxs,
    fontWeight: '700',
    textAlign: 'center',
  },
  transcriptText: {
    color: '#3D2850',
    fontSize: storybookTheme.type.sm,
    lineHeight: 21,
    fontWeight: '600',
    textAlign: 'center',
  },
  transcriptConfirmCard: {
    minHeight: 92,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: '#E0C5EC',
    backgroundColor: '#F7EFFA',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
    paddingVertical: 16,
  },
  transcriptConfirmText: {
    color: '#321A4A',
    fontSize: storybookTheme.type.lg,
    lineHeight: 31,
    fontWeight: '700',
    textAlign: 'center',
  },
  fallbackText: {
    color: '#7C7081',
    fontSize: storybookTheme.type.xs,
    lineHeight: 19,
    textAlign: 'center',
  },
  completeMark: {
    color: '#D09A19',
    fontSize: storybookTheme.type.xxl,
    fontWeight: '700',
    textAlign: 'center',
  },
  parentReportContent: { width: '100%', gap: 20 },
  reportHero: {
    borderRadius: 28,
    borderWidth: 2,
    borderColor: '#DCD1FF',
    backgroundColor: '#FFFFFF',
    padding: 28,
    gap: 14,
    shadowColor: '#2E1948',
    shadowOpacity: 0.08,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 10 },
  },
  reportEyebrow: {
    color: '#F07C58',
    fontSize: storybookTheme.type.xs,
    fontWeight: '700',
    letterSpacing: 1.5,
  },
  reportHeroTitle: {
    color: '#2C1749',
    fontSize: storybookTheme.type.xxl,
    lineHeight: 42,
    fontWeight: '700',
  },
  reportStoryPill: {
    alignSelf: 'flex-start',
    borderRadius: storybookTheme.radius.pill,
    backgroundColor: '#FFF4E3',
    paddingHorizontal: 15,
    paddingVertical: 9,
  },
  reportStoryPillText: {
    color: '#35204D',
    fontSize: storybookTheme.type.sm,
    fontWeight: '700',
  },
  reportHeroBody: {
    color: '#746987',
    fontSize: storybookTheme.type.md,
    lineHeight: 25,
  },
  reportStats: { gap: 10 },
  reportStatsWide: { flexDirection: 'row' },
  reportStatCard: {
    flex: 1,
    minHeight: 104,
    borderRadius: 20,
    backgroundColor: '#FFF6E8',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 15,
  },
  reportStatValue: {
    color: '#2E174D',
    fontSize: storybookTheme.type.xxl,
    lineHeight: 38,
    fontWeight: '700',
  },
  reportStatLabel: {
    color: '#756983',
    fontSize: storybookTheme.type.sm,
    fontWeight: '600',
  },
  reportPanel: {
    borderRadius: 28,
    backgroundColor: '#FFFFFF',
    padding: 28,
    gap: 12,
    shadowColor: '#2E1948',
    shadowOpacity: 0.07,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
  },
  reportPanelTitle: {
    color: '#2D1949',
    fontSize: storybookTheme.type.xl,
    lineHeight: 33,
    fontWeight: '700',
  },
  reportPanelDescription: {
    color: '#746987',
    fontSize: storybookTheme.type.sm,
    lineHeight: 22,
  },
  reportQuestionList: { gap: 18, marginTop: 8 },
  reportQuestionCard: {
    borderRadius: storybookTheme.radius.card,
    backgroundColor: '#FFF7E9',
    padding: 20,
    gap: 16,
  },
  reportQuestionHeader: { gap: 12 },
  reportQuestionHeaderWide: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  reportQuestionNumber: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#FFC813',
    alignItems: 'center',
    justifyContent: 'center',
  },
  reportQuestionNumberText: {
    color: '#2D1948',
    fontSize: storybookTheme.type.md,
    fontWeight: '700',
  },
  reportQuestionHeading: { flex: 1, alignItems: 'flex-start', gap: 9 },
  reportQuestionText: {
    color: '#2D1948',
    fontSize: storybookTheme.type.lg,
    lineHeight: 31,
    fontWeight: '700',
  },
  reportQuestionType: {
    borderRadius: storybookTheme.radius.pill,
    backgroundColor: '#E9DDFD',
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  reportQuestionTypeText: {
    color: '#4B3269',
    fontSize: storybookTheme.type.xs,
    fontWeight: '700',
  },
  reportSceneFigure: {
    borderRadius: 19,
    overflow: 'hidden',
    backgroundColor: '#FFFFFF',
  },
  reportSceneImage: {
    width: '100%',
    aspectRatio: 1.6,
    backgroundColor: '#E9DFC9',
  },
  reportSceneCaption: {
    minHeight: 45,
    justifyContent: 'center',
    paddingHorizontal: 15,
    paddingVertical: 10,
    backgroundColor: '#FFFFFF',
  },
  reportSceneCaptionText: {
    color: '#716481',
    fontSize: storybookTheme.type.xs,
    lineHeight: 18,
    fontWeight: '600',
  },
  reportSelectedPath: {
    borderRadius: 18,
    backgroundColor: '#FFFFFF',
    padding: 17,
    gap: 4,
  },
  reportSelectedPathEyebrow: {
    color: '#EF7653',
    fontSize: storybookTheme.type.xxs,
    fontWeight: '700',
  },
  reportSelectedPathTitle: {
    color: '#2F1C49',
    fontSize: storybookTheme.type.md,
    lineHeight: 23,
    fontWeight: '700',
  },
  reportSelectedPathSummary: {
    color: '#746987',
    fontSize: storybookTheme.type.sm,
    lineHeight: 20,
  },
  reportStoryDevelopment: {
    borderTopWidth: 1,
    borderTopColor: '#EEE6F2',
    marginTop: 9,
    paddingTop: 11,
    gap: 5,
  },
  reportStoryDevelopmentLabel: {
    color: '#7B5AA1',
    fontSize: storybookTheme.type.xxs,
    fontWeight: '700',
  },
  reportStoryDevelopmentText: {
    color: '#4E4058',
    fontSize: storybookTheme.type.sm,
    lineHeight: 21,
    fontWeight: '500',
  },
  reportEmptyState: {
    borderRadius: 21,
    backgroundColor: '#FFF7E9',
    padding: 22,
    gap: 7,
    marginTop: 8,
  },
  reportEmptyTitle: {
    color: '#33204B',
    fontSize: storybookTheme.type.md,
    fontWeight: '700',
  },
  reportEmptyBody: { color: '#756983', fontSize: storybookTheme.type.sm, lineHeight: 21 },
  reportCoachPanel: {
    borderRadius: 28,
    borderWidth: 2,
    borderColor: '#DCD1FF',
    backgroundColor: '#FFFFFF',
    padding: 28,
    gap: 12,
  },
  reportCoachSummary: {
    borderRadius: 20,
    backgroundColor: '#FFF6E8',
    padding: 21,
  },
  reportCoachSummaryText: {
    color: '#35204D',
    fontSize: storybookTheme.type.md,
    lineHeight: 29,
    fontWeight: '700',
  },
  reportEvidenceBox: {
    borderRadius: 20,
    backgroundColor: '#FFFDF8',
    borderWidth: 1,
    borderColor: '#EEE6D8',
    padding: 20,
    gap: 9,
  },
  reportBulletRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
  },
  reportBulletMark: {
    color: '#C24A2E', // WCAG AA 4.5:1 (원래 #E46647은 흰/크림 배경에서 3.34:1로 미달)
    fontSize: storybookTheme.type.md,
    lineHeight: 22,
    fontWeight: '700',
  },
  reportBulletText: {
    flex: 1,
    color: '#4E4058',
    fontSize: storybookTheme.type.sm,
    lineHeight: 21,
    fontWeight: '500',
  },
  reportFocusBox: {
    borderRadius: 20,
    backgroundColor: '#F2ECFF',
    padding: 20,
    gap: 10,
  },
  reportFocusLabel: {
    color: '#3B2854',
    fontSize: storybookTheme.type.sm,
    fontWeight: '700',
  },
  reportFocusChips: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  reportFocusChip: {
    borderRadius: storybookTheme.radius.pill,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  reportFocusChipText: {
    color: '#392650',
    fontSize: storybookTheme.type.xs,
    fontWeight: '700',
  },
  reportFocusNote: {
    color: '#786D87',
    fontSize: storybookTheme.type.xs,
    lineHeight: 19,
  },
  reportFollowUpList: { gap: 10, marginTop: 6 },
  reportFollowUpCard: {
    borderRadius: 18,
    backgroundColor: '#FFF7E9',
    padding: 17,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  reportFollowUpNumber: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#FFC813',
    alignItems: 'center',
    justifyContent: 'center',
  },
  reportFollowUpNumberText: {
    color: '#2E1948',
    fontSize: storybookTheme.type.sm,
    fontWeight: '700',
  },
  reportFollowUpText: {
    flex: 1,
    color: '#35204D',
    fontSize: storybookTheme.type.md,
    lineHeight: 24,
    fontWeight: '600',
  },
  reportActivity: {
    borderRadius: 20,
    backgroundColor: '#DFF6E6',
    padding: 20,
    gap: 5,
    marginTop: 3,
  },
  reportActivityTitle: {
    color: '#22623A',
    fontSize: storybookTheme.type.md,
    fontWeight: '700',
  },
  reportActivityBody: {
    color: '#345F43',
    fontSize: storybookTheme.type.sm,
    lineHeight: 22,
  },
  reportActionPanel: {
    borderRadius: 28,
    backgroundColor: '#4A287A',
    padding: 28,
    gap: 20,
  },
  reportActionPanelWide: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  reportActionCopy: { flex: 1, gap: 7 },
  reportActionEyebrow: {
    alignSelf: 'flex-start',
    color: '#2D1948',
    backgroundColor: '#FFE36E',
    fontSize: storybookTheme.type.xxs,
    fontWeight: '700',
    letterSpacing: 1,
    paddingHorizontal: 5,
    paddingVertical: 2,
  },
  reportActionTitle: {
    color: '#FFFFFF',
    fontSize: storybookTheme.type.lg,
    lineHeight: 30,
    fontWeight: '700',
  },
  reportActionBody: {
    color: '#DDD2EB',
    fontSize: storybookTheme.type.sm,
    lineHeight: 21,
  },
  reportActionButtons: { minWidth: 230, gap: 9 },
  reportPrimaryAction: {
    minHeight: 54,
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  reportPrimaryActionText: {
    color: '#35204E',
    fontSize: storybookTheme.type.md,
    fontWeight: '700',
  },
  reportSecondaryAction: {
    flex: 1,
    minHeight: 42,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.35)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
  },
  reportSecondaryActionText: {
    color: '#FFFFFF',
    fontSize: storybookTheme.type.xs,
    fontWeight: '700',
    textAlign: 'center',
  },
  reportSecondaryActionRow: { flexDirection: 'row', gap: 9 },
  /**
   * modalScrim/modalCard/modalEyebrow/modalTitle은 shared/ui/modal.tsx의 Modal 컴포넌트로
   * 옮겨갔다. modalBody/modalTextButton*는 home-menu-modal.tsx가 Modal의 고정 액션 슬롯에
   * 안 맞는 2단계 위저드라 children으로 직접 마크업을 유지하면서 여전히 참조한다.
   */
  modalBody: {
    color: '#706476',
    fontSize: storybookTheme.type.sm,
    lineHeight: 21,
    textAlign: 'center',
  },
  modalTextButton: {
    minHeight: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalTextButtonLabel: {
    color: '#6A4B7C',
    fontSize: storybookTheme.type.xs,
    fontWeight: '700',
    textDecorationLine: 'underline',
  },
  companionChatProfileRow: {
    alignItems: 'center',
    gap: 6,
    marginBottom: 2,
  },
  companionChatAvatarFrame: {
    width: 64,
    height: 64,
    borderRadius: 32,
    overflow: 'hidden',
    backgroundColor: '#F0E7F7',
    borderWidth: 2,
    borderColor: '#F6C64D',
  },
  companionChatAvatarImage: {
    position: 'absolute',
  },
  companionChatProfileName: {
    color: '#28153F',
    fontSize: storybookTheme.type.sm,
    fontWeight: '700',
  },
  companionChatHistory: { maxHeight: 220 },
  companionChatTurn: { gap: 4, marginBottom: 12 },
  companionChatChildText: {
    alignSelf: 'flex-end',
    color: '#FFFFFF',
    backgroundColor: '#6E428B',
    borderRadius: 14,
    borderBottomRightRadius: 4,
    paddingHorizontal: 12,
    paddingVertical: 8,
    fontSize: storybookTheme.type.sm,
    fontWeight: '500',
    maxWidth: '85%',
  },
  companionChatSpinner: { alignSelf: 'flex-start', marginTop: 4 },
  companionChatReplyText: {
    alignSelf: 'flex-start',
    color: '#28153F',
    backgroundColor: '#F0E7F7',
    borderRadius: 14,
    borderBottomLeftRadius: 4,
    paddingHorizontal: 12,
    paddingVertical: 8,
    fontSize: storybookTheme.type.sm,
    fontWeight: '500',
    maxWidth: '85%',
  },
  companionChatErrorText: {
    alignSelf: 'flex-start',
    color: '#8C3E1F',
    fontSize: storybookTheme.type.xs,
    fontWeight: '500',
  },
  exitReasonList: { gap: 8 },
  exitReasonButton: {
    minHeight: 46,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#DDD0E5',
    backgroundColor: '#F7F1FA',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  exitReasonButtonText: {
    color: '#4E3267',
    fontSize: storybookTheme.type.sm,
    fontWeight: '600',
  },
  parentMessage: {
    borderRadius: 15,
    borderWidth: 1,
    borderColor: '#DFC773',
    backgroundColor: '#FFF4CE',
    padding: 14,
    gap: 5,
  },
  parentMessageTitle: { color: '#6B5119', fontSize: storybookTheme.type.xs, fontWeight: '700' },
  parentMessageText: { color: '#6B5119', fontSize: storybookTheme.type.xs, lineHeight: 19 },
  parentMessageAction: {
    color: '#4A2B61',
    fontSize: storybookTheme.type.xs,
    fontWeight: '700',
    marginTop: 3,
  },
});
