// Generated by scripts/generate-story-package.mjs. Do not edit manually.
import { buildStoryRuntimePackage, type StoryRuntimePackage } from './story-package';
import type { GeneratedStoryContent, StoryPackageData } from './story-package-types';
import { STORY_AUDIO_ASSETS_BY_ID, STORY_IMAGE_ASSETS_BY_ID } from './story-assets.generated';
import content_HG from '../hansel-gretel/generated-story-content.json';
import data_HG from '../hansel-gretel/story-package.generated.json';

const package_HG = buildStoryRuntimePackage({
  generatedContent: content_HG as unknown as GeneratedStoryContent,
  packageData: data_HG as unknown as StoryPackageData,
  imageAssets: STORY_IMAGE_ASSETS_BY_ID["HG"] ?? {},
  audioAssets: STORY_AUDIO_ASSETS_BY_ID["HG"] ?? {},
});

export const STORY_PACKAGES_BY_ID: Readonly<Record<string, StoryRuntimePackage>> = {
  "HG": package_HG,
};
export const DEFAULT_BETA_STORY_ID = "HG";
